### ISSUE TITLE
State of the repo?

### ISSUE THREAD

**Issue by JeffSpies** [monolithlabs/fast-trie#1]
Hi, Jason/@jd20,

Was this implementation complete? I'm interested in using to perform range queries on a set of integers.

Thanks!

**Comment by jd20** [comment]
Hi @JeffSpies, apologies I haven't worked on this repo in a long time, I think range queries should work, but use at your own risk (I never had time to add tests or use thoroughly).

**Comment by JeffSpies** [comment]
Thanks, Jason! Did you happen to have a source/inspiration for the implementation?
